# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'edgaroAzureSubscription092019(1fbe7963-8a53-4dd9-a5cb-cef8f01b77c5)'
    appType: 'webApp'
    WebAppName: 'v-edcaroWinReactWevApp'
    packageForLinux: '$(System.DefaultWorkingDirectory)\**\Application*.zip'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'
    TakeAppOfflineFlag: false
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.14'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn run build
  displayName: 'npm install and build'
