# Node.js with React
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'edgaroAzureSubscription092019 (1fbe7963-8a53-4dd9-a5cb-cef8f01b77c5)'
    appType: 'webApp'
    appName: 'v-edcaroWinReactJSWebApp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g create-react-app
    npm install
    yarn run build
  displayName: 'npm install and build'
